config/routes.rb
Rails.application.routes.draw do
  resources :units
  resources :payers
  resources :buildings
  resources :communities
  resources :clients

end

app/models/community.rb
class Community < ActiveRecord::Base
  belongs_to :client
  has_many :buildings
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.all
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:name, :client_id)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.erb
<%= form_for(@community) do |f| %>
  <% if @community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
      <% @community.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.text_field :client_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/communities/edit.html.erb
<h1>Editing Community</h1>

<%= render 'form' %>

<%= link_to 'Show', @community %> |
<%= link_to 'Back', communities_path %>

app/views/communities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Communities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @communities.each do |community| %>
      <tr>
        <td><%= community.name %></td>
        <td><%= community.client %></td>
        <td><%= link_to 'Show', community %></td>
        <td><%= link_to 'Edit', edit_community_path(community) %></td>
        <td><%= link_to 'Destroy', community, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Community', new_community_path %>

app/views/communities/new.html.erb
<h1>New Community</h1>

<%= render 'form' %>

<%= link_to 'Back', communities_path %>

app/views/communities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @community.name %>
</p>

<p>
  <strong>Client:</strong>
  <%= @community.client %>
</p>

<%= link_to 'Edit', edit_community_path(@community) %> |
<%= link_to 'Back', communities_path %>